### ISSUE TITLE
print_solution fails for OSR model

### ISSUE THREAD

**Issue by donihue** [jmaih/RISE_toolbox#171]
Hello,
I tried to use print_solution on the example model 'usmodel_ms_lc'. 
The "howto" file is: 
close all
clc
gdexo=rise('usmodel_ms_lc');
gdexo=solve(gdexo);
print_solution(gdexo)

It failed with the error cited below. 
It seems that RISE believes that there are 2 régimes, but the output model contains only 1 régime.
Is there a work-around for this problem?

Regards
donihue

======================================================================
dsge:: Exogenous Switching Optimal Simple Rule (OSR) model in 2 regimes detected
dsge:: model has both backward and forward-looking components
    20     0    20

MODEL  SOLUTION #1/1
SOLVER :: rise_1

Regime    1 : const = 1 & loosecommit = 1 

..................

Index exceeds the number of array elements (1).
Error in dsge/print_solution
Error in dsge/print_solution>print_solution_engine
Error in dsge/print_solution
Error in howto (line 5)
print_solution(gdexo) 

======================================================================

**Comment by jmaih** [comment]
Hi Donihe,

Did you change anything to the file?

Line 72 is commented out. Because of this, there are less equations than
the number of endogenous variables. In such a situation, in the presence of
a planner objective, RISE should detect an optimal policy model and not an
OSR model, which occurs when the number of equations is equal to the
number of endogenous variables.

Cheers,

J.

**Comment by donihue** [comment]
Thank you so much for your quick reply.
Indeed, I had put that line back in, as when it is left out (as in the original) I receive the error below:
==================================================================================
parse:: Derivatives of dynamic model wrt y(+0-), x and theta up to order 1. 81 equations and 148 variables :0.3097 seconds
Warning:  the following parameters do not seem to affect model
usmodel_ms_lc. You may want to discard them from model for tidiness 
> In format_parameters
  In dsge
  In rise (line 64)
  In howto (line 3) 
    'crdy'    'crhoas'    'crhols'    'crpi'    'crr'    'cry'
 
dsge:: Exogenous Switching Optimal Policy model in 2 regimes detected
dsge:: model has both backward and forward-looking components

MODEL  HAS NOT BEEN SOLVED AT LEAST UP TO THE FIRST ORDER

**Comment by jmaih** [comment]
Now the model is correctly parsed but I don't know what you do afterwards.

Whatever you want to do requires the model to be solved first.

The model does not solve either because
- it has not been parameterized (some parameters are missing values) : give
values to the missing parameters
- the number of iterations is reached before the tolerance criterion :
increase the number of iterations. You can investigate this issue either by
deciphering the retcode or by setting the 'debug' option to true
- there is no solution : possibly a bad parameterization

Cheers

J.

**Comment by donihue** [comment]
Thanks again for the quick reply.
So far as I can tell, the model is identical to that originally included in the RISE tool-box, so the parametrisation should be OK. And I do nothing afterwards! 
I attach the files below

[usmodel_ms_lc_v9.txt](https://github.com/jmaih/RISE_toolbox/files/9235270/usmodel_ms_lc_v9.txt)
[howto_jc9.txt](https://github.com/jmaih/RISE_toolbox/files/9235272/howto_jc9.txt)

**Comment by jmaih** [comment]
What I said earlier stands :)

try the following

`solve(gdexo,'fix_point_maxiter',3500)`

or if you want to see the iterations

`solve(gdexo,'fix_point_verbose',true,'fix_point_maxiter',3500)`

**Comment by donihue** [comment]
Sorry to come back to this, but the above fix does not solve the problem: the model still fails to solve, although RISE stops iterating after 3024 iterations.

I must be failing to understand something in the functioning of RISE. It seems strange that the very model you used in your Loose Commitment article does not solve when attempting Loose Commitment in RISE. That same model (with the same parametrisation) works perfectly in other circumstances under RISE. 

Regards
donihue

**Comment by jmaih** [comment]
"It seems strange that the very model you used in your Loose Commitment
article does not solve when attempting Loose Commitment in RISE"

I beg your pardon ???

There is nothing strange. I gave you all the explanations possible.

What did you do with the model after 3024? Why do you think the iterations
stopped at 3024? Have you used RISE before?

**Comment by donihue** [comment]
I apologise if I have offended you. Indeed, I have not used RISE before, and that is undoubtedly why I am failing here. 

I simply attempted to run directly from the RISE installation the model "usmodel_ms_lc.rs" found in the StochasticReplanning folder. As there was no corresponding "howto.m" file, I tried to construct one of my own. That is undoubtedly where I failed to understand something.  I was hoping to compare the results with those found in your paper. 

Again, my apologies for any offense; it was certainly not intended.
Regards
donihue

**Comment by jmaih** [comment]
Please run the piece of code I sent you earlier with the increased number
of iterations and then when the iterations have stopped, run

print_estimation_results(m)

where m is the model object.

As far as comparison is concerned, the file you are running was not meant
or intended as a replication of the results in our paper. Some parameters
might be different, the tolerance criteria, etc. Also, the original code I
wrote was running on dynare and I made some changes and improvements when
writing the RISE version. Nevertheless I would expect the results to be
the same if all the inputs are the same.

Cheers,
J.

**Comment by donihue** [comment]
Thank you for your patience with me! I greatly appreciate it.

I did as you suggested but still could not find a solution:

===================================
close all
clc
gdexo=rise('usmodel_ms_lc');
solve(gdexo,'fix_point_maxiter',10000,'fix_point_verbose',true)
print_solution(gdexo)
........
iter # 3022 : conv(x)=0.00000002, conv(F(x))=0.00000002
iter # 3023 : conv(x)=0.00000001, conv(F(x))=0.00000001
iter # 3024 : conv(x)=0.00000001, conv(F(x))=0.00000001
ans = 
  rise with properties:

        user_data: []
            nsols: 1
      definitions: [1×1 struct]
        equations: [1×1 struct]
    folders_paths: []
         filename: 'usmodel_ms_lc'
           legend: ''
       endogenous: [1×1 struct]
        exogenous: [1×1 struct]
       parameters: [1×1 struct]
      observables: [1×1 struct]
          options: [1×1 struct]
       estimation: [1×1 struct]
         solution: [1×1 struct]
    markov_chains: [1×1 struct]

MODEL  HAS NOT BEEN SOLVED AT LEAST UP TO THE FIRST ORDER
===================================

I had assumed that as the parametrisation of "usmodel_ms_lc.rs" was identical to that of the other SW2007 models in various parts of the "examples" folder, it would be a good place to start. Evidently that was a bad assumption! Unfortunately, I have no idea what to do next.

Thank you also for your comments regarding the comparison to your paper. As I was never able to find the "companion codes" mentioned in footnote 4 of the paper, I was hoping that using "usmodel_ms_lc.rs" would do the trick, hence my futile attempts to get some results from it.

Regards
donihue

**Comment by jmaih** [comment]
The output you posted suggests that the model is solved.

Can we have a quick zoom/teams/phone call meeting so that I can understand
exactly what you are doing?

**Comment by donihue** [comment]
Certainly. Thank you very much. How to do that?

**Comment by jmaih** [comment]
Whatever you prefer. Here is a Teams link
https://teams.live.com/meet/9492176053306
If that doesn't work we do something else

**Comment by jmaih** [comment]
Shall we try zoom perhaps?

**Comment by donihue** [comment]
That should work. Will you send me a link?

**Comment by jmaih** [comment]
https://us04web.zoom.us/j/73345583308?pwd=4Ar3KZl3PLyC_DQFWOeFCuylAlldbd.1
